Добавлено получение данных и отправка данных
htmlacademy-javascript/1610043-kekstagram-23 pull request #11
Opened 2021-07-12 19:29 UTC by Omuriev

2021-07-12 20:58 UTC, bzvyagintsev requested changes

2021-07-12 20:58 UTC, bzvyagintsev commented on js/api.js
> +      }
Аналогично:

```
if(response.ok) {
  return response.json();
}

return showAlert('Не удалось загрузить данные с сервера.');
```

2021-07-12 20:58 UTC, bzvyagintsev commented on js/api.js
> +    .then((posts) => onSuccess(posts))
Аналогично:

`.then(onSuccess)`

2021-07-12 20:58 UTC, bzvyagintsev commented on js/api.js
> +    .catch(() => {
Можно без фигурных скобок

2021-07-12 20:58 UTC, bzvyagintsev commented on js/api.js
> +    })
Тут тоже можно с ретёрном реализовать алгоритм, как выше.

2021-07-12 20:58 UTC, bzvyagintsev commented on js/api.js
> +    .catch(() => {
И тут без фигурных скобок

2021-07-12 20:58 UTC, bzvyagintsev commented on js/render-pictures.js
> +  similarPosts = posts;
Не очень понимаю, что ты тут делаешь, но ты копируешь по ссылке

2021-07-12 20:58 UTC, bzvyagintsev commented on js/util.js
> +  });
А вот тут обработчик ты ставишь на документ, после удаления модалки, он останется

2021-07-12 20:58 UTC, bzvyagintsev commented on js/util.js
> +  });
Аналогично

2021-07-12 20:58 UTC, bzvyagintsev commented on js/util.js
> +  document.addEventListener('keydown', (evt) => {
можно сразу деструкторизовать: ({keyCode})

2021-07-13 09:14 UTC, Omuriev commented on js/render-pictures.js
> +  similarPosts = posts;
Мне нужно в эвент листенер передавать список, и я ничего лучше не придумал, чем так делать

2021-07-15 01:36 UTC, bzvyagintsev commented on js/api.js
>        } else {
Прикол в том, чтобы убрать else

У тебя либо ретёрн в if сработает, либо после if. Else тебе не нужен

2021-07-15 01:36 UTC, bzvyagintsev commented on js/api.js
>        } else {
Аналогично

2021-07-15 01:44 UTC, bzvyagintsev commented on js/render-pictures.js
> +let similarPosts = [];
Это название переводится как "похожие посты"

2021-07-15 01:44 UTC, bzvyagintsev commented on js/render-pictures.js
>  picturesContainer.addEventListener('click', (evt) => {
У тебя теперь в постах с бэка приходят айдишники, и на них можно завязаться

2021-07-15 01:44 UTC, merged