Добавил открытие модалки большого изображения, отображение данных в н…
htmlacademy-javascript/1610043-kekstagram-23 pull request #6
Opened 2021-06-18 09:54 UTC by Omuriev

…ем и закрытие

2021-06-18 11:35 UTC, bzvyagintsev commented on js/render-big-picture.js
> +bigPictureCancelButton.addEventListener('click', () => {
1. По-хорошему, тебе надо создавать обработчик этого события при открытие модалки и при закрытие удалять его.
2. Наверно, можно так: `bigPictureCancelButton.addEventListener('click', closeBigPictureModal)`

2021-06-18 11:35 UTC, bzvyagintsev commented on js/render-big-picture.js
> +document.addEventListener('keydown', (evt) => {
То же самое, обработчик надо создать на открытие модалки, и при закрытие удалить его.

2021-06-18 11:39 UTC, bzvyagintsev commented on js/render-pictures.js
> +
Это будешь удалять?

2021-06-18 11:49 UTC, bzvyagintsev requested changes

2021-06-18 11:49 UTC, bzvyagintsev commented on js/render-big-picture.js
> +  commentsContainer.appendChild(generateComments(comments));
https://developer.mozilla.org/en-US/docs/Web/API/Element/append

2021-06-18 11:49 UTC, bzvyagintsev commented on js/render-big-picture.js
> +  comments.forEach(({avatar, message, name}) => {
И можно попробовать использовать [reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) и сделать, чтобы функция сразу возвращала готовый массив:

`
const generateComments = (comments) => comments.reduce(...);
`

Тогда никаких доп. переменных и push() использовать не надо

2021-06-18 11:49 UTC, bzvyagintsev commented on js/render-big-picture.js
> +  comments.forEach(({avatar, message, name}) => {
P.S. reduce не мутирует массив, поэтому можно смело его использовать без клонирования объекта.

2021-06-20 00:29 UTC, bzvyagintsev commented on js/render-big-picture.js
> +  generateComments(comments).forEach((element) => {
Глянь доку по методу `append`. Ты можешь передать в этот метод массив комментариев, и тебе не надо будет делать цикл `forEach`. В этом и была идея.

2021-06-20 00:30 UTC, bzvyagintsev commented on js/render-pictures.js
> +  if(target.className === 'picture__img') {
Перед `=` и после `if` нужны пробелы

2021-06-20 00:34 UTC, bzvyagintsev commented on js/render-big-picture.js
> +const checkKeyCode = (evt) => {
Лучше назвать более релевантно, типа onEscButton. У тебя функция начинается с check (проверка), а внутри вызывает сайдэффект закрытия модалки

2021-06-20 06:50 UTC, Omuriev commented on js/render-big-picture.js
> +  generateComments(comments).forEach((element) => {
При использовании append без forEach (т.е commentsContainer.append(generateComments(comments))) вместо комментов вставляется [object HTMLLIElement],[object HTMLLIElement]

2021-06-20 20:58 UTC, bzvyagintsev commented on js/render-pictures.js
> +  const target = evt.target;
На будущее, можно тоже деструкторизовать: const { target } = evt;

2021-06-20 20:58 UTC, merged