Добавлена загрузка комментариев по 5 штук
htmlacademy-javascript/1610043-kekstagram-23 pull request #9
Opened 2021-06-29 11:27 UTC by Omuriev

2021-06-30 20:18 UTC, bzvyagintsev requested changes

2021-06-30 20:18 UTC, bzvyagintsev commented on js/render-big-picture.js
> +  commentsContainer.append(...generatedComments.splice(0, 5));
Меня смущает, что splice — мутирует исходник, т.е. удаляет из него элементы. А, по-хорошему, тебе надо исходник оставить неизменным.

2021-06-30 20:18 UTC, bzvyagintsev commented on js/render-big-picture.js
>  const closeBigPictureModal = () => {
Чувак, а если сделать так:  

У тебя есть два варианты закрыть окно: клик на иконку и нажатие на ESC. Ты можешь сделать два обработчика onCloseClick() onEscPress(), в них вызывать функцию closeBigPictureModal(), которая будет скрывать окно и удалять обработчики.  

Получится так? На мой взгляд такая цепочка функций будет норм выглядить.

2021-07-01 11:26 UTC, Omuriev commented on js/render-big-picture.js
>  const closeBigPictureModal = () => {
Не получится, потому что если я перенесу удаление обработчика внутрь closeBigPictureModal(), то мне придется onCloseClick() и onEscPress() писать в коде выше, чем closeBigPictureModal(),(что бы еслинт не ругался) а если я напишу выше, то ес линт будет ругаться на то, что closeBigPictureModal() вызывается до объявления в  onCloseClick() и onEscPress()

2021-07-02 02:57 UTC, bzvyagintsev commented on js/render-big-picture.js
> +  commentsContainer.append(...generatedComments.slice(0, commentsCount));
Работает, но я не понимаю почему. `append` — добавляет элементы в конец списка. А ты на каждое нажатие `showComments` вызываешь `slice` от 0 до n. Т.е. ты берёшь сначала от 0 до 5, потом от 0 до 10 и т.д. И, по идеи, `append` должен к первым 5 элементам добавить 10 элементов (включая те же первые 5 элементов) и т.д.

Короче, подобные алгоритмы обычно реализуются таким образом, что догружаются только следующие n элементов. Сначала 0-5, потом 5-10, потом 10-15 и тд.

2021-07-02 02:58 UTC, merged